.catalog:
  name: "GitLab Server"
  version: "v9.1.0"
  description: "Git repository server with continuous integration and docker."
  uuid: gitlab-0
  minimum_rancher_version: v1.5.5
  questions:
      - variable: "gitlab_hostname"
        description: "Gitlab hostname (without uri scheme http:// or https://)"
        label: "Hostname:"
        required: true
        default: "git.example.com"
        type: "string"
      - variable: "ssh_port"
        description: "SSH port to expose on host. Will be used to bind TCP"
        label: "SSH port:"
        required: true
        default: 22
        type: "string"

gitlab-server:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

gitlab-data:
  scale: 1
  retain_ip: true