version: '2'
services:
  gitlab-server:
    image: gitlab/gitlab-ce:11.11.8-ce.0
    hostname: ${gitlab_hostname}
    ports:
    - ${ssh_port}:22/tcp
    volumes:
    - ${DIR}/etc:/etc/gitlab
    - ${DIR}/log:/var/log/gitlab
    - ${DIR}/opt:/var/opt/gitlab
